[package]
name = "explorer-jobs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
explorer-domain.workspace = true
explorer-win.workspace = true
explorer-store = { path = "../explorer-store" }
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
serde.workspace = true
uuid.workspace = true
