[package]
name = "explorer-index"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
explorer-domain.workspace = true
explorer-win.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json = { workspace = true }
uuid = { workspace = true }
rusqlite = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
